app = "breatheeasyapp" # Replace with your app name

[build]
  image = "breatheeasyapp" # Ensure it points to your Dockerfile

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80  # External HTTP port
    handlers = ["http"]
