app = "meteodata" # Replace with your app name

[build]
  image = "fedihamdi/breatheeasyapp" # Ensure it points to your Dockerfile

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80  # External HTTP port
    handlers = ["http"]
