name: Docker Builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change directory to src/reaper/
        run: ls

      - name: Build the Docker image
        run: |
          cd ./src/reaper/data_nc
          docker build -t meteodata:$(date +\%s) -f Dockerfile .
