name: Pylint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9.18, 3.10.13]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint==3.0.1
      - name: Analysing the code with pylint
        run: |
          pylint --disable R0801,C0114,C0103,C0116,E0401,C0115,W0718,R1710,W0718 $(git ls-files '*.py')
